language: elixir

elixir:
  - 1.4.2

otp_release:
  - 19.1

cache:
  directories:
    - deps
    - _build

env:
  - MIX_ENV=test

addons:
  postgresql: '9.4'

services:
  - postgresql

before_script:
  - cp config/{travis,test}.exs
  - mix do ecto.create, ecto.migrate

script:
  - mix credo --strict
  - mix coveralls.travis
